export const initialTransactions = [
    {
        id: 1,
        description: "Salário de março",
        amount: 1850.00,
        type: "income",
        date: "2024-03-25",
    },
    {
        id: 2,
        description: "Renda do apartamento",
        amount: 650.00,
        type: "expense",
        date: "2024-03-26",
    },
    {
        id: 3,
        description: "Supermercado Pingo Doce",
        amount: 87.40,
        type: "expense",
        date: "2024-03-27",
    },
    {
        id: 4,
        description: "Trabalho freelance",
        amount: 320.00,
        type: "income",
        date: "2024-03-28",
    },
    {
        id: 5,
        description: "NOS - internet e telemóvel",
        amount: 45.00,
        type: "expense",
        date: "2024-03-29",
    },
    {
        id: 6,
        description: "Jantar com clientes",
        amount: 112.80,
        type: "expense",
        date: "2024-03-30",
    },
    {
        id: 7,
        description: "Reembolso de viagem",
        amount: 95.00,
        type: "income",
        date: "2024-03-31",
    },
    {
        id: 8,
        description: "Ginásio Holmes Place",
        amount: 39.90,
        type: "expense",
        date: "2024-04-01",
    },
]